version: '3.8'

services:
  app:
    build: ./app
    env_file:
      - ./.env
    ports:
      - 8000:8000

  mongodb:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo_data:/var/lib/mongo/
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  redis:
    image: "redis:alpine"

  celery:
    build: ./app
    command: celery -A core.celery worker --beat -l info
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - redis
      - app
      - mongodb

volumes:
  mongo_data: